/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{vue,js,ts,jsx,tsx}',
    './public/index.html',
  ],
  theme: {
    extend: {
      colors: {
        // Neo-Brutalist color system - matching reference design
        'background': '#131313',
        'surface-container-highest': '#353535',
        'surface-container-high': '#2a2a2a',
        'surface-container': '#1f1f1f',
        'surface-container-low': '#1b1b1b',
        'surface-container-lowest': '#0e0e0e',
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-variant': '#353535',
        'primary-container': '#ffd700',
        'primary': '#fff6df',
        'primary-fixed': '#ffe16d',
        'primary-fixed-dim': '#e9c400',
        'on-primary': '#3a3000',
        'on-primary-fixed': '#221b00',
        'on-primary-fixed-variant': '#544600',
        'on-primary-container': '#705e00',
        'secondary-container': '#007f7f',
        'secondary': '#76d6d5',
        'secondary-fixed': '#93f2f2',
        'secondary-fixed-dim': '#76d6d5',
        'on-secondary': '#003737',
        'on-secondary-fixed': '#002020',
        'on-secondary-fixed-variant': '#004f4f',
        'on-secondary-container': '#ddfffe',
        'tertiary-container': '#00f1ff',
        'tertiary': '#defcff',
        'tertiary-fixed': '#79f5ff',
        'tertiary-fixed-dim': '#00dbe8',
        'on-tertiary': '#00363a',
        'on-tertiary-fixed': '#002022',
        'on-tertiary-fixed-variant': '#004f54',
        'on-tertiary-container': '#006a70',
        'error-container': '#93000a',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'on-background': '#e2e2e2',
        'on-surface': '#e2e2e2',
        'on-surface-variant': '#d0c6ab',
        'inverse-surface': '#e2e2e2',
        'inverse-on-surface': '#303030',
        'inverse-primary': '#705d00',
        'outline': '#999077',
        'outline-variant': '#4d4732',
        'surface-tint': '#e9c400',
        // Short aliases for convenience
        'surfaceHigh': '#2a2a2a',
        'surfaceHighest': '#353535',
        'surfaceLow': '#1b1b1b',
        'surfaceLowest': '#0e0e0e',
        'text': '#e2e2e2',
        'text-muted': '#666666',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Space Grotesk', 'sans-serif'],
      },
      borderRadius: {
        'none': '0px',
        'DEFAULT': '0px',
        'lg': '0px',
        'xl': '0px',
        'full': '9999px',
      },
      borderWidth: {
        '4': '4px',
        '2': '2px',
      },
      boxShadow: {
        'neo-black': '8px 8px 0px 0px rgba(0, 0, 0, 1)',
        'neo-white': '6px 6px 0px 0px rgba(255, 255, 255, 1)',
        'neo-gold': '8px 8px 0px 0px #ffd700',
        'neo-teal': '8px 8px 0px 0px #007f7f',
        'neo-small': '4px 4px 0px 0px rgba(0, 0, 0, 1)',
        'neo-hard': '6px 6px 0px 0px rgba(53, 53, 53, 1)',
        'neo-hover': '12px 12px 0px 0px rgba(0, 0, 0, 1)',
        'sidebar': '8px 0px 0px 0px rgba(0, 127, 127, 1)',
      },
      spacing: {
        '72': '72px',
        '88': '88px',
        '120': '120px',
      },
      screens: {
        'mobile': '768px',
        'tablet': '1024px',
      },
      skew: {
        '-1': '-1deg',
        '-2': '-2deg',
        '-3': '-3deg',
        '1': '1deg',
        '2': '2deg',
        '3': '3deg',
      },
      animation: {
        'spin-slow': 'spin 2s linear infinite',
      },
    },
  },
  plugins: [],
  prefix: '',
  corePlugins: {
    preflight: true,
  },
}